@startuml
Evento -- Conferencia
BoardMeeting --|> Evento
BoardMiembro --|> Miembro
Miembro --|> Persona


Asociacion o-- "0..*" Evento
Asociacion o-- "0..*" Persona
BoardMeeting "0..*" -- "0..*" BoardMiembro : Asiste a
Persona "0..*" -- "0..*" Conferencia : Asiste a
Evento "0..*" -- "1" Localizacion : Se encuenta en
Evento "0..*" -- "0..*" Miembro : Asiste a
Asociacion o-- "0..*" Localizacion

class Asociacion{
}
class Miembro{
}
class BoardMiembro{}
class Evento{
}
class Conferencia{
}
class Localizacion{
}
class BoardMeeting{}
class Persona{
}
@enduml