@startuml
Asociacion o-- Evento
Asociacion o-- Persona
Asociacion o-- Localizacion
Evento -- Conferencia
BoardMeeting --|> Evento
Evento -- Miembro : asiste a
Localizacion -- Evento : Se encuentra en
BoardMiembro --|> Miembro
Miembro --|> Persona
Conferencia -- Persona : asiste a
BoardMiembro -- BoardMeeting : asiste a


class Asociacion{
newLocation(l : Location) : void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register(m : Member,e : Event) : void
}
class Miembro{
email : String
}
class BoardMiembro{}
class Evento{
fecha : Date
descripcion : String
assign(l : Location) : void
}
class Conferencia{
n_maxPersonas : int
}
class Localizacion{
descripcion : String
direccion: String
}
class BoardMeeting{}
class Persona{
nombre : String
}
@enduml